# This script calculates final segmentation metrics (DSC, IoU, Sens, Prec, HD95) 
# by comparing the 3D-cleaned ROIs generated by your model against your manual ground-truth masks.

import cv2
import numpy as np
import argparse
from pathlib import Path
from tqdm import tqdm
from medpy.metric.binary import hd95

def evaluate_metrics(preds_dir, truths_dir):
    preds_dir = Path(preds_dir)
    truths_dir = Path(truths_dir)
    
    print(f"Scanning for prediction images in {preds_dir}...")
    pred_paths = list(preds_dir.rglob("*.bmp"))
    
    if not pred_paths:
        print("No .bmp files found in the predictions directory.")
        return

    print(f"Evaluating {len(pred_paths)} images...")

    total_dsc, total_iou, total_sens, total_prec = 0, 0, 0, 0
    hd95_scores = []
    
    # Wrap the loop in tqdm for a progress bar
    loop = tqdm(pred_paths, desc="Calculating Metrics")
    
    for pred_path in loop:
        # Reconstruct the path to find the matching ground-truth mask
        relative_path = pred_path.relative_to(preds_dir)
        truth_path = truths_dir / relative_path
        
        if not truth_path.exists():
            print(f"\nWarning: Missing ground truth for {relative_path}. Skipping.")
            continue
            
        # Load images as grayscale
        pred_img = cv2.imread(str(pred_path), cv2.IMREAD_GRAYSCALE)
        truth_img = cv2.imread(str(truth_path), cv2.IMREAD_GRAYSCALE)
        
        # Binarize to strict 0 and 1 arrays
        p = (pred_img > 127).astype(np.uint8)
        t = (truth_img > 127).astype(np.uint8)
        
        # 1. Fast Overlap Math
        TP = (p * t).sum()
        FP = ((p == 1) & (t == 0)).sum()
        FN = ((p == 0) & (t == 1)).sum()
        
        dsc = (2. * TP) / (2. * TP + FP + FN + 1e-6)
        iou = TP / (TP + FP + FN + 1e-6)
        sens = TP / (TP + FN + 1e-6)
        prec = TP / (TP + FP + 1e-6)
        
        total_dsc += dsc
        total_iou += iou
        total_sens += sens
        total_prec += prec
        
        # 2. HD95 Spatial Math
        # HD95 crashes if either image is completely blank. 
        if p.max() > 0 and t.max() > 0:
            score = hd95(p, t)
            hd95_scores.append(score)
            loop.set_postfix(hd95=f"{score:.2f} px")
            
    # Calculate Final Averages
    num_images = len(pred_paths)
    avg_dsc = total_dsc / num_images
    avg_iou = total_iou / num_images
    avg_sens = total_sens / num_images
    avg_prec = total_prec / num_images
    avg_hd95 = np.mean(hd95_scores) if len(hd95_scores) > 0 else float('nan')
    
    print("\n" + "="*50)
    print("FINAL 3D-CLEANED METRICS REPORT")
    print("="*50)
    print(f"Dice Similarity (DSC): {avg_dsc:.4f}")
    print(f"Intersection/Union (IoU): {avg_iou:.4f}")
    print(f"Sensitivity (Recall):  {avg_sens:.4f}")
    print(f"Precision (PPV):       {avg_prec:.4f}")
    print(f"Hausdorff Distance 95: {avg_hd95:.2f} px")
    print("="*50)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Evaluate 3D-Cleaned MicroCT Segments")
    parser.add_argument("--preds", type=str, required=True, help="Path to the generated ROIs (e.g., data/inference/output_tibia)")
    parser.add_argument("--truths", type=str, required=True, help="Path to the manual ground-truth masks (e.g., data/macro_tibia/masks)")
    
    args = parser.parse_args()
    evaluate_metrics(args.preds, args.truths)